TYPO3:
  PackageBuilder:
    javaScripts:
      packageBuilder:
        files:
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/panels/insertElementsPanel.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/app.js'
        sorting: 200

    backport:
      targetFolder:
    extendIceSettings: TRUE
    userinterfaceSettings:
      title: Package Builder

    projectElementGroups:
      packageElements:
        sorting: 200
        label: 'Package elements'

      model:
        sorting: 400
        label: 'Model'
        enableTypes:
          - Model
          - Property
          - Relation'


    projectElementTypes:
      'TYPO3.PackageBuilder:Base':
        options:
          editors:
            elementType:
              sorting: 100
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextOutput'
              templateName: 'ElementOptionsPanel-PropertyPanelTitle'

      'TYPO3.PackageBuilder:Container':
        options:
          label: ''
          _isCompositeRenderable: true

      'TYPO3.PackageBuilder:Package':
        options:
          label: ''
          _isCompositeRenderable: false
          _isTopLevel: true
          editors:
            label:
              label: 'Package Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'
            packageKey:
              sorting: 200
              label: 'Package key'
              propertyPath: 'identifier'
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'

      # group packageElements
      'TYPO3.PackageBuilder:Model':
        label: ''
        options:
          label: 'Model'
          group: packageElements
          _isCompositeRenderable: true
          sorting: 100
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'

      'TYPO3.PackageBuilder:Plugin':
        options:
          label: 'Plugin'
          group: packageElements
          sorting: 110
          editors:
            label:
              label: 'Plugin Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'

      'TYPO3.PackageBuilder:Module':
        options:
          label: 'Backend-Module'
          group: packageElements
          sorting: 120
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'
            key:
              label: 'Key'
              propertyPath: 'key'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'

      'TYPO3.PackageBuilder:Service':
        options:
          label: 'Service'
          group: packageElements
          sorting: 130
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'

      'TYPO3.PackageBuilder:Scheduler':
        options:
          label: 'Scheduler'
          group: packageElements
          sorting: 140

      'TYPO3.PackageBuilder:Property':
        options:
          label: 'Property'
          group: 'model'
          sorting: 120
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'
            propertyType:
              sorting: 200
              label: 'Property Type'
              propertyPath: 'propertyType'
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.SelectEditor'
              availableElements:
                0:
                  value: ['string']
                  label: 'String'
                1:
                  value: ['text']
                  label: 'Text'
                2:
                  value: ['RichText']
                  label: 'RichText'
                3:
                  value: ['Integer']
                  label: 'Integer'
                4:
                  value: ['Float']
                  label: 'Float'
                5:
                  value: ['Boolean']
                  label: 'Boolean'
                6:
                  value: ['DateTime']
                  label: 'DateTime'
                7:
                  value: ['Select']
                  label: 'Select'
                8:
                  value: ['Image']
                  label: 'Image'

      'TYPO3.PackageBuilder:Relation':
        options:
          label: 'Relation'
          group: 'model'
          sorting: 120
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.TextEditor'
            relationType:
              sorting: 200
              label: 'Relation Type'
              propertyPath: 'relationType'
              viewName: 'TYPO3.Ice.View.ElementOptionsPanelClass.Editor.SelectEditor'
              availableElements:
                0:
                  value: ['zeroToOne']
                  label: '1:1'
                1:
                  value: ['manyToOne']
                  label: 'n:1'
                2:
                  value: ['oneToMany']
                  label: '1:n'
                3:
                  value: ['manyToMany']
                  label: 'm:n'

